POST localhost:8080/api/feature/type/wizard
Content-Type: application/json

{
  "requiredLevel": 1,
  "name": "Sculpt Spells",
  "description": "Skill issue fireball casting feat",
  "modifiers": [
    {
      "modifierType": "AC_BONUS",
      "modifierValue": "INT"
    }
  ]
}

###
POST localhost:8080/api/feature/type/wizard
Content-Type: application/json

{
  "requiredLevel": 3,
  "name": "Magic Missile Spam",
  "description": "Just throws a lot of glowing darts.",
  "modifiers": [
    {
      "modifierType": "DAMAGE_BONUS",
      "modifierValue": "1d4+1"
    }
  ]
}

###
GET localhost:8080/api/feature/type/wizard
###
PUT localhost:8080/api/feature/0
Content-Type: application/json

{
  "requiredLevel": 2,
  "name": "Action Surge",
  "description": "Push yourself beyond your normal limits for a moment. On your turn, you can take one additional action on top of your regular action and a possible bonus action.",
  "modifiers": [
    {
      "modifierType": "AC_BONUS",
      "modifierValue": "1"
    }
  ]
}
###

DELETE localhost:8080/api/feature/1

###
GET localhost:8080/api/subclass/wizard

###
POST localhost:8080/api/subclass/wizard
Content-Type: application/json

{
  "name": "School of Evocation",
  "description": "Generic wizard subclass",
  "features": [
    {
      "requiredLevel": 1,
      "name": "Sculpt Spells",
      "description": "Skill issue fireball casting feat",
      "modifiers": [
        {
          "modifierType": "AC_BONUS",
          "modifierValue": "INT"
        }
      ]
    },

    {
      "requiredLevel": 3,
      "name": "Magic Missile Spam",
      "description": "Just throws a lot of glowing darts.",
      "modifiers": [
        {
          "modifierType": "DAMAGE_BONUS",
          "modifierValue": "1d4+1"
        }
      ]
    }

  ]
}
###
PUT localhost:8080/api/subclass/School of Evocation
Content-Type: application/json

  {
    "name": "Path of the Berserker",
    "description": "A path of untrammeled fury, fraught with blood and thrills.",
    "features": [
      {
        "requiredLevel": 3,
        "name": "Frenzy",
        "description": "You can go into a frenzy when you rage, allowing you to make a single melee weapon attack as a bonus action.",
        "modifiers": [
          {
            "modifierType": "DAMAGE_BONUS",
            "modifierValue": "1"
          }
        ]
      },
      {
        "requiredLevel": 6,
        "name": "Mindless Rage",
        "description": "You can't be charmed or frightened while raging.",
        "modifiers": [
          {
            "modifierType": "DAMAGE_BONUS",
            "modifierValue": "CHARMED"
          },
          {
            "modifierType": "DAMAGE_BONUS",
            "modifierValue": "FRIGHTENED"
          }
        ]
      }
    ]
  }

###
DELETE localhost:8080/api/subclass/School of Evocation
###
POST localhost:8080/api/spell
Content-Type: application/json

{
  "name": "Fireball",
  "description": "A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame.",
  "schoolOfMagic": "Evocation",
  "level": 3,
  "range": "150ft",
  "duration": "Instantaneous",
  "isConcentration": false,
  "isAttack": true,
  "damage": [
    {
      "die": 6,
      "diceCount": 8,
      "damageType": "FIRE"
    }
  ],
  "spellComponent": {
    "somatic": true,
    "material": true,
    "verbal": true
  },
  "castingTime": {
    "actionCastTime": "ACTION",
    "time": null
  }
}
###
POST localhost:8080/api/spell/wizard/Fireball
###
POST localhost:8080/api/spell
Content-Type: application/json

{
  "name": "Haste",
  "description": "Choose a willing creature that you can see within range. Until the spell ends, the target's speed is doubled, it gains a +2 bonus to AC, it has advantage on Dexterity saving throws, and it gains an additional action on each of its turns.",
  "schoolOfMagic": "Transmutation",
  "level": 3,
  "range": "touch",
  "duration": "1 minute",
  "isConcentration": true,
  "isAttack": false,
  "damage": [],
  "spellComponent": {
    "somatic": true,
    "material": true,
    "verbal": true
  },
  "castingTime": {
    "actionCastTime": "ACTION",
    "time": null
  }
}

###
POST localhost:8080/api/spell/wizard/Haste
###
GET localhost:8080/api/spell/get_all/wizard

###
PUT localhost:8080/api/spell
Content-Type: application/json

{
  "name": "Haste",
  "description": "You choose one object that you must touch throughout the casting of the spell. If it is a magic item or some other magic-imbued object, you learn its properties and how to use them.",
  "schoolOfMagic": "Divination",
  "level": 1,
  "range": "touch",
  "duration": "Instantaneous",
  "isConcentration": false,
  "isAttack": false,
  "damage": [],
  "spellComponent": {
    "somatic": true,
    "material": true,
    "verbal": true
  },
  "castingTime": {
    "actionCastTime": "TIME",
    "time": 10
  }
}

###
DELETE localhost:8080/api/spell/Haste

###
POST localhost:8080/api/class
Content-Type: application/json

{
  "name": "Fighter",
  "description": "A master of martial combat, skilled with a variety of weapons and armor.",
  "hitDie": 10,
  "amountOfSkillsToChoose": 2,
  "abilityScoreImprovements": [4, 6, 8, 12, 14, 16, 19],
  "cantripsKnownPerLevel": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  "features": [
    {
      "requiredLevel": 1,
      "name": "Fighting Style (Archery)",
      "description": "You gain a +2 bonus to attack rolls you make with ranged weapons.",
      "modifiers": [
        { "modifierType": "ATTACK_BONUS", "modifierValue": "2" }
      ]
    },
    {
      "requiredLevel": 1,
      "name": "Second Wind",
      "description": "Regain 1d10 + level HP as a bonus action.",
      "modifiers": [
        { "modifierType": "ACTION_GAIN", "modifierValue": "1" }
      ]
    }
  ],
  "multiClassRequirement": "STR",
  "spellcastingAbility": "NUL",
  "casterType": "NONE",
  "proficiency": {
    "skills": ["ATHLETICS", "ACROBATICS"],
    "armourProficiencies": ["HEAVY", "MEDIUM", "LIGHT", "SHIELD"],
    "weaponProficiencies": ["Simple Weapons", "Martial Weapons"],
    "toolsProficiencies": []
  },
  "startingEquipment": [
    {
      "optionA": [{ "name": "Chain Mail", "count": 1 }],
      "optionB": [{ "name": "Leather Armor", "count": 1 }, { "name": "Longbow", "count": 1 }]
    }
  ],
  "user_created": false
}


###
POST localhost:8080/api/class
Content-Type: application/json

{
  "name": "Wizard",
  "description": "A scholarly magic-user capable of manipulating reality.",
  "hitDie": 6,
  "amountOfSkillsToChoose": 2,
  "abilityScoreImprovements": [4, 8, 12, 16, 19],
  "cantripsKnownPerLevel": [3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
  "features": [
    {
      "requiredLevel": 2,
      "name": "Sculpt Spells",
      "description": "Create pockets of relative safety within the effects of your evocation spells.",
      "modifiers": [
        { "modifierType": "SAVE_SUCCESS_AUTO", "modifierValue": "0" }
      ]
    }
  ],
  "multiClassRequirement": "INT",
  "spellcastingAbility": "INT",
  "casterType": "FULL",
  "proficiency": {
    "skills": ["ARCANA", "HISTORY"],
    "armourProficiencies": [],
    "weaponProficiencies": ["Daggers", "Quarterstaffs"],
    "toolsProficiencies": []
  },
  "startingEquipment": [
    {
      "optionA": [{ "name": "Quarterstaff", "count": 1 }],
      "optionB": [{ "name": "Dagger", "count": 1 }]
    }
  ],
  "user_created": false
}

###
GET localhost:8080/api/class/get_names

###

GET localhost:8080/api/class/Wizard

###

GET localhost:8080/api/class/Fighter

###
PUT localhost:8080/api/class
Content-Type: application/json

{
  "name": "Fighter",
  "description": "A holy warrior bound by a sacred oath.",
  "hitDie": 10,
  "amountOfSkillsToChoose": 2,
  "abilityScoreImprovements": [4, 8, 12, 16, 19],
  "cantripsKnownPerLevel": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  "features": [
    {
      "requiredLevel": 6,
      "name": "Aura of Protection",
      "description": "Grant a bonus to saving throws to nearby allies.",
      "modifiers": [
        { "modifierType": "SAVE_BONUS", "modifierValue": "3" }
      ]
    }
  ],
  "multiClassRequirement": "STR",
  "spellcastingAbility": "CHA",
  "casterType": "HALF",
  "proficiency": {
    "skills": ["PERSUASION", "RELIGION"],
    "armourProficiencies": ["HEAVY", "MEDIUM", "LIGHT", "SHIELD"],
    "weaponProficiencies": ["Martial Weapons"],
    "toolsProficiencies": []
  },
  "startingEquipment": [
    {
      "optionA": [{ "name": "Warhammer", "count": 1 }, { "name": "Shield", "count": 1 }],
      "optionB": [{ "name": "Martial Weapon", "count": 2 }]
    }
  ],
  "user_created": false
}

###
DELETE localhost:8080/api/class/Wizard

