-- Class section of DB

CREATE TABLE IF NOT EXISTS types(
    name VARCHAR(128) NOT NULL PRIMARY KEY ,
    description VARCHAR(1024) NOT NULL,
    hit_die INT NOT NULL,
    amount_of_skills_to_choose INT NOT NULL,
    ability_score_improvements INT NOT NULL, -- as we have 20 levels we can pack all the info into int :)
    multiclass_requirement VARCHAR(3) NOT NULL,
    spellcasting_ability VARCHAR(3) NOT NULL,
    caster_type VARCHAR(16) NOT NULL,
    user_created boolean

);

CREATE TABLE IF NOT EXISTS cantrips_per_level(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level INT NOT NULL,
    cantrips INT NOT NULL,
    type_name VARCHAR(128)

);

CREATE TABLE IF NOT EXISTS starting_equipment(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR(128) NOT NULL,
    name VARCHAR(128) NOT NULL,
    count INT NOT NULL,
    index INT NOT NULL,
    option_a boolean
);


CREATE TABLE IF NOT EXISTS subclasses(
    name VARCHAR(128) NOT NULL PRIMARY KEY,
    type_name VARCHAR(128) NOT NULL,
    description VARCHAR(1024) NOT NULL,
    user_created boolean
);

CREATE TABLE IF NOT EXISTS spells(
  name VARCHAR(128) NOT NULL PRIMARY KEY,
  description  VARCHAR(1024) NOT NULL,
  school_of_magic VARCHAR(128) NOT NULL,
  level INT NOT NULL,
  range VARCHAR(32) NOT NULL,
  duration VARCHAR(32) NOT NULL,
  is_concentration BOOLEAN,
  is_attack BOOLEAN,
  user_created BOOLEAN,
  spell_component INT, -- we will do a little trick with binary representation to effectively store 3 bools
  casting_time VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS spell_lists(
    owner_name VARCHAR(128),
    spell_name VARCHAR(128),
    PRIMARY KEY (owner_name,spell_name)

);

CREATE TABLE IF NOT EXISTS spells_damage(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  spell_name VARCHAR(128),
  die INT NOT NULL,
  dice_count INT NOT NULL,
  damage_type VARCHAR(128)

);

CREATE TABLE IF NOT EXISTS type_proficiencies(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
  type_name VARCHAR(128) NOT NULL,
  proficiency_type VARCHAR(16) NOT NULL,
  proficiency VARCHAR(32) NOT NULL

);


-- one to be used in all
CREATE TABLE IF NOT EXISTS features(
    id INT PRIMARY KEY , -- I guess it should be auto generated here?
    owner_type VARCHAR(128) NOT NULL,
    owner_name VARCHAR(128) NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(1024) NOT NULL,
    required_level INT NOT NULL,
    user_created BOOLEAN
);

CREATE TABLE IF NOT EXISTS modifiers(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_id INT NOT NULL,
    modifier_type VARCHAR(64) NOT NULL,
    modifier_value VARCHAR(64) NOT NULL


);