-- Class section of DB

CREATE TABLE IF NOT EXISTS types(
                    name VARCHAR(128) NOT NULL PRIMARY KEY ,
                    hit_dice INT NOT NULL,
                    description VARCHAR(1024) NOT NULL
);


CREATE TABLE IF NOT EXISTS subclasses(
    name VARCHAR(128) NOT NULL PRIMARY KEY,
    type_name VARCHAR(128) NOT NULL,
    description VARCHAR(1024) NOT NULL,
    user_created boolean
);



-- one to be used in all
CREATE TABLE IF NOT EXISTS features(
    id INT PRIMARY KEY ,
    owner_type VARCHAR(128) NOT NULL,
    owner_name VARCHAR(128) NOT NULL ,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(1024) NOT NULL,
    required_level INT NOT NULL,
    user_created BOOLEAN
);

CREATE TABLE IF NOT EXISTS modifiers(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_id INT NOT NULL,
    modifier_type VARCHAR(64) NOT NULL,
    modifier_value VARCHAR(64) NOT NULL


);