-- Class section of DB

CREATE TABLE IF NOT EXISTS types(
                    name VARCHAR(128) NOT NULL PRIMARY KEY ,
                    hit_dice INT NOT NULL,
                    description VARCHAR(1024) NOT NULL
);


CREATE TABLE IF NOT EXISTS subclasses(
    name VARCHAR(128) NOT NULL PRIMARY KEY,
    type_name VARCHAR(128) NOT NULL,
    description VARCHAR(1024) NOT NULL,
    user_created boolean
);

CREATE TABLE IF NOT EXISTS spells(
  name VARCHAR(128) NOT NULL PRIMARY KEY,
  description  VARCHAR(1024) NOT NULL,
  school_of_magic VARCHAR(128) NOT NULL,
  level INT NOT NULL,
  range VARCHAR(32) NOT NULL,
  duration VARCHAR(32) NOT NULL,
  is_concentration BOOLEAN,
  is_attack BOOLEAN,
  user_created BOOLEAN,
  spell_component INT, -- we will do a little trick with binary representation to effectively store 3 bools
  casting_time VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS spell_lists(
    owner_name VARCHAR(128),
    spell_name VARCHAR(128),
    PRIMARY KEY (owner_name,spell_name)

);

CREATE TABLE IF NOT EXISTS spells_damage(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  spell_name VARCHAR(128),
  die INT NOT NULL,
  dice_count INT NOT NULL,
  damage_type VARCHAR(128)

);


-- one to be used in all
CREATE TABLE IF NOT EXISTS features(
    id INT PRIMARY KEY ,
    owner_type VARCHAR(128) NOT NULL,
    owner_name VARCHAR(128) NOT NULL ,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(1024) NOT NULL,
    required_level INT NOT NULL,
    user_created BOOLEAN
);

CREATE TABLE IF NOT EXISTS modifiers(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_id INT NOT NULL,
    modifier_type VARCHAR(64) NOT NULL,
    modifier_value VARCHAR(64) NOT NULL


);